

plotx = (fliplr(VarName3'));

plot(plotx, '--rs',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')
xlabel('Frequenz kHz')
ylabel('Frequenzschritt')

plotx = ((VarName2));

plot(plotx, '--rs',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')

ylabel('Frequenz kHz')
xlabel('Frequenzschritt')