

plotx = (fliplr(VarName2'));

plot(plotx,1:150, '--rs',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')
xlabel('Frequenz kHz')
ylabel('Frequenzschritt')

plotx = ((VarName3));

plot(plotx, '--rs',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g')

ylabel('Frequenz kHz')
xlabel('Frequenzschritt')